language: ruby
rvm:
  - 1.9.3
  - 2.2.1
gemfile:
  - gemfiles/actionmailer_3.0.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_3.0.0_capybara_2.4.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_3.1.0_capybara_2.4.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_3.2.0_capybara_2.4.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_4.0.0_capybara_2.4.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_4.1.0_capybara_2.4.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_1.0.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_1.1.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_2.0.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_2.1.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_2.2.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_2.3.0.gemfile
  - gemfiles/actionmailer_4.2.0_capybara_2.4.0.gemfile
